# Generated by Django 5.0.4 on 2024-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='medico',
            name='sobrenome',
            field=models.CharField(default='', max_length=200, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(default='', max_length=200, verbose_name='Nome'),
        ),
    ]
