# Generated by Django 5.0.4 on 2024-06-04 15:18

import medicos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_agenda_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(help_text='Insira uma data para agenda', validators=[medicos.models.validar_dia]),
        ),
    ]
