# Generated by Django 5.0.4 on 2024-05-22 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_especialidade_valor_consulta_medico_sobrenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='O número precisa estar neste formato: (00) 00000-0000 ou (00) 0000-0000', regex='^\\(?\\d{2}\\)?[\\s.-]?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
