# Generated by Django 5.0.4 on 2024-05-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_medico_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculimo', 'Masculino')], default='', max_length=9),
        ),
    ]
