# Generated by Django 5.0.4 on 2024-06-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_alter_medico_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 ás 08:00'), ('2', '08:00 ás 09:00'), ('3', '09:00 ás 10:00'), ('4', '10:00 ás 11:00'), ('5', '11:00 ás 12:00'), ('6', '13:00 ás 14:00'), ('7', '14:00 ás 15:00'), ('8', '15:00 ás 16:00'), ('9', '16:00 ás 17:00'), ('10', '17:00 ás 18:00')], max_length=10),
        ),
    ]
