# Generated by Django 5.0.4 on 2024-06-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status_pag_cons',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo_pag_cons',
            field=models.CharField(choices=[('Convênio', 'Convênio'), ('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], default='', max_length=10),
        ),
    ]
