# Generated by Django 5.0.4 on 2024-06-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='motivo',
            field=models.CharField(blank=True, max_length=199, null=True),
        ),
    ]
