# Generated by Django 5.0.4 on 2024-06-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(default='0000-00-00', verbose_name='nascimento'),
        ),
    ]
