# Generated by Django 5.0.4 on 2024-05-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_convenio', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='00000000', max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(default='2000-01-01', verbose_name='nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='seu_email@email.com', max_length=300, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=30, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='num_carteirinha',
            field=models.IntegerField(blank=True, default=0, verbose_name='carteirinha'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default='', max_length=50, verbose_name='sobrenome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status_cad_pac',
            field=models.BooleanField(default=True, verbose_name='ativar cadastro'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='laudo',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='motivo',
            field=models.CharField(default='', max_length=199),
        ),
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status_cons',
            field=models.CharField(choices=[('Concluída', 'Concluída'), ('Cancelada', 'Cancelada'), ('Agendada', 'Agendada'), ('Remarcada', 'Remarcada')], default=(('Concluída', 'Concluída'), ('Cancelada', 'Cancelada'), ('Agendada', 'Agendada'), ('Remarcada', 'Remarcada')), max_length=10),
        ),
        migrations.AddField(
            model_name='consulta',
            name='status_pag_cons',
            field=models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], default=(('Pago', 'Pago'), ('Pendente', 'Pendente')), max_length=10),
        ),
        migrations.AddField(
            model_name='consulta',
            name='tipo_pag_cons',
            field=models.CharField(choices=[('Convênio', 'Convênio'), ('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], default=(('Convênio', 'Convênio'), ('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')), max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.convenio', verbose_name='convênio'),
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_exame', models.CharField(max_length=30)),
                ('valor_exame', models.FloatField()),
                ('tipo_pag_ex', models.CharField(choices=[('Convênio', 'Convênio'), ('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=10)),
                ('status_pag_ex', models.CharField(choices=[('Pago', 'Pago'), ('Pendente', 'Pendente')], max_length=10)),
                ('id_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('L_esf_OD', models.CharField(max_length=30, null=True)),
                ('L_esf_OE', models.CharField(max_length=30, null=True)),
                ('L_cil_OD', models.CharField(max_length=30, null=True)),
                ('L_cil_OE', models.CharField(max_length=30, null=True)),
                ('L_eixo_OD', models.CharField(max_length=30, null=True)),
                ('L_eixo_OE', models.CharField(max_length=30, null=True)),
                ('L_dp_OD', models.CharField(max_length=30, null=True)),
                ('L_dp_OE', models.CharField(max_length=30, null=True)),
                ('P_esf_OD', models.CharField(max_length=30, null=True)),
                ('P_esf_OE', models.CharField(max_length=30, null=True)),
                ('P_cil_OD', models.CharField(max_length=30, null=True)),
                ('P_cil_OE', models.CharField(max_length=30, null=True)),
                ('P_eixo_OD', models.CharField(max_length=30, null=True)),
                ('P_eixo_OE', models.CharField(max_length=30, null=True)),
                ('P_dp_OD', models.CharField(max_length=30, null=True)),
                ('P_dp_OE', models.CharField(max_length=30, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.consulta')),
            ],
        ),
    ]
