# Generated by Django 5.0.4 on 2024-06-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_nasc',
            field=models.DateField(default='2000-01-01', verbose_name='nascimento'),
        ),
    ]
