# Generated by Django 5.0.4 on 2024-06-04 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_sexo_alter_cliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='laudo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='sintomas',
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=199)),
                ('sintomas', models.TextField(max_length=2000)),
                ('observacoes', models.TextField(max_length=2000)),
                ('laudo', models.TextField(max_length=2000)),
                ('consulta', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.consulta')),
            ],
        ),
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
