# Generated by Django 5.0.4 on 2024-06-03 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_consulta_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='laudo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='sintomas',
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=199, null=True)),
                ('sintomas', models.TextField(blank=True, max_length=2000, null=True)),
                ('observacoes', models.TextField(blank=True, max_length=2000, null=True)),
                ('laudo', models.TextField(blank=True, max_length=2000, null=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_prontuario', to='clientes.consulta')),
            ],
        ),
    ]
