# Generated by Django 5.0.4 on 2024-06-03 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_consulta_laudo_remove_consulta_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='consulta',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta_prontuario', to='clientes.consulta'),
        ),
    ]
