# Generated by Django 5.0.4 on 2024-06-03 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_prontuario_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulta_prontuario', to='clientes.consulta'),
        ),
    ]
