# Generated by Django 5.0.4 on 2024-06-03 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_prontuario_consulta_consulta_prontuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='prontuario',
        ),
        migrations.AddField(
            model_name='prontuario',
            name='consulta',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clientes.consulta'),
        ),
    ]
